const codes = [
    "0000001",
    "0000002",
    "0000003",
    "0000005",
    "0000006",
    "0000007",
    "0000010",
    "0000011",
    "0000012",
    "0000014",
    "0000016",
    "0000017",
    "0000018",
    "0000019",
    "0000023",
    "0000025",
    "0000026",
    "0000030",
    "0000031",
    "0000035",
    "0000039",
    "0000043",
    "0000049",
    "0000050",
    "0000051",
    "0000053",
    "0000054",
    "0000055",
    "0000057",
    "0000059",
    "0000060",
    "0000063",
    "0000064",
    "0000065",
    "0000066",
    "0000068",
    "0000070",
    "0000072",
    "0000074",
    "0000075",
    "0000076",
    "0000083",
    "0500001",
    "0500002",
    "0500003",
    "0500004",
    "0500005",
    "0500006",
    "0500007",
    "0500008",
    "0500011",
    "0500012",
    "0500013",
    "0500014",
    "0500202",
    "0500016",
    "0300003",
    "0300009",
    "0300010",
    "0300011",
    "0300014",
    "0300020",
    "0300023",
    "0300025",
    "0300026",
    "0300028",
    "0300029",
    "0300042",
    "0300045",
    "0300046",
    "0300048",
    "0300050",
    "0300051",
    "0300056",
    "0300057",
    "0300059",
    "0300062",
    "0300063",
    "0300066",
    "0300067",
    "0300070",
    "0300074",
    "0300076",
    "0300077",
    "0300078",
    "0300079",
    "0300081",
    "0300083",
    "0300085",
    "0300087",
    "0300089",
    "0300090",
    "0300091",
    "0300092",
    "0300096",
    "0300097",
    "0300099",
    "0300100",
    "0300102",
    "0300104",
    "0300105",
    "0300106",
    "0300108",
    "0300109",
    "0300111",
    "0300113",
    "0300114",
    "0300115",
    "0300117",
    "0300118",
    "0300120",
    "0300122",
    "0300123",
    "0300128",
    "0300129",
    "0300131",
    "0300135",
    "0300142",
    "0300143",
    "0300146",
    "0300148",
    "0300149",
    "0600001",
    "0600002",
    "0600003",
    "0700001",
    "0700005",
    "0700006",
    "0700007",
    "0700009",
    "0700010",
    "0700011",
    "0700012",
    "0700013",
    "0700014",
    "0700016",
    "0700017",
    "0700018",
    "0700019",
    "0700020",
    "0700021",
    "0700023",
    "0700024",
    "0700026",
    "0000066-NOHC",
    "0000068-NOHC",
    "0000083-NOHC",
    "0000057-NOHC",
    "0000001-NOHC",
    "0000014-NOHC",
    "0000007-NOHC",
    "0000031-NOHC",
    "1000001",
    "1000002",
    "1000003",
    "1000004",
    "1000005",
    "1000006",
    "1000007",
    "1000008",
    "1000009",
  ];
  
  const names = [
    "KCB Bank Kenya Limited",
    "Standard Chartered Bank Kenya Limited",
    "ABSA Bank Kenya PLC",
    "Bank of India",
    "Bank of Baroda (Kenya) Ltd",
    "NCBA Kenya PLC",
    "Prime Bank Ltd",
    "Co-operative Bank of Kenya Limited",
    "National Bank of Kenya Ltd",
    "M-Oriental Bank Limited",
    "Citibank N.A. Kenya",
    "Habib Bank AG Zurich",
    "Middle East Bank Kenya Limited",
    "Bank of Africa Kenya Limited",
    "Consolidated Bank of Kenya Ltd",
    "Credit Bank Limited",
    "Access Bank (Kenya) Limited",
    "Chase Bank (K) Limited",
    "Stanbic Bank Kenya Limited",
    "African Banking Corporation Limited",
    "Imperial Bank Ltd",
    "Ecobank Kenya Limited",
    "Spire Bank Ltd",
    "Paramount Bank Limited",
    "Kingdom Bank Limited",
    "Guaranty Trust Bank (Kenya) Limited",
    "Victoria Commercial Bank Limited",
    "Guardian Bank Limited",
    "I&M Bank Ltd",
    "Development Bank of Kenya Ltd",
    "SBM Bank (Kenya) Limited",
    "Diamond Trust Bank (K) Limited",
    "Charterhouse Bank Ltd",
    "Mayfair CIB Bank Limited",
    "Sidian Bank Limited",
    "Equity Bank Kenya Limited",
    "Family Bank Limited",
    "Gulf African Bank Limited",
    "First Community Bank Ltd",
    "DIB Bank Kenya Limited",
    "UBA Kenya Bank Limited",
    "HFC Limited",
    "Faulu Microfinance Bank Limited",
    "Kenya Women Microfinance Bank PLC",
    "SMEP Microfinance Bank Limited",
    "Key Microfinance Bank Limited",
    "Rafiki Microfinance Bank Limited",
    "Century Microfinance Bank Limited",
    "Sumac Microfinance Bank Limited",
    "U & I Microfinance Bank Limited",
    "Daraja Microfinance Bank Limited",
    "Caritas Microfinance Bank Limited",
    "Maisha Microfinance Bank Limited",
    "UWEZO Microfinance Bank Limited",
    "Choice Microfinance Bank Limited",
    "Muungano Microfinance Bank Limited",
    "Alpha Forex Bureau Ltd",
    "Aristocrats Forex Bureau Ltd",
    "Bamburi Forex Bureau Ltd",
    "Bay Forex Bureau (Nairobi) Ltd",
    "Muthaiga-ABC Forex Bureau Ltd",
    "Central Forex Bureau Ltd",
    "Classic Forex Bureau Limited",
    "Commercial Forex Bureau Limited",
    "Conference Forex Bureau Company Limited",
    "Continental Forex Bureau Ltd",
    "Cosmos Forex Bureau Ltd",
    "Forex Bureau Afro Ltd",
    "Gateway Forex Bureau Ltd",
    "Giant Forex Bureau de Change Ltd",
    "Give and Take Forex Bureau Ltd",
    "Glory Forex Bureau Ltd",
    "GNK Forex Bureau Ltd",
    "Industrial Area Forex Bureau Ltd",
    "Island Forex Bureau Ltd",
    "Junction Forex Bureau Limited",
    "Kenza Exchange Bureau Ltd",
    "La’che Forex Bureau Ltd",
    "Leo Forex Bureau Ltd",
    "Link Forex Bureau Ltd",
    "Maritime Forex Bureau Ltd",
    "Middletown Forex Bureau Ltd",
    "Mona Bureau De Change Ltd",
    "Moneypoint Forex Bureau Ltd",
    "Morgan Forex Bureau De Change Ltd",
    "Mustaqbal Forex Bureau Ltd",
    "Nairobi Bureau De Change Ltd",
    "Namanga Forex Bureau Ltd",
    "Nawal Forex Bureau Ltd",
    "Offshore Forex Bureau Limited",
    "Pacific Forex Bureau Limited",
    "Peaktop Bureau De Change Ltd",
    "Pearl Forex Bureau Ltd",
    "Pel Forex Bureau Ltd",
    "Pwani Forex Bureau Ltd",
    "Avenue Forex Bureau Limited",
    "Regional Forex Bureau Limited",
    "Rift Valley Forex Bureau Ltd",
    "Satellite Forex Bureau Ltd",
    "Simba Forex Bureau Limited",
    "Sky Forex Bureau Limited",
    "Solid Exchange Bureau Ltd",
    "Sterling Forex Bureau Ltd",
    "Sunny Forex Bureau Limited",
    "Taipan Forex Bureau Ltd",
    "Trade Bureau De Change Ltd",
    "Travel Point Forex Bureau Limited",
    "Travellers Forex Bureau Ltd",
    "Union Forex Bureau Ltd",
    "Victoria Forex Bureau De Change Ltd",
    "Wallstreet Bureau De Change Ltd",
    "Westlands Forex Bureau Ltd",
    "Yaya Centre Exchange Bureau Ltd",
    "Green Exchange Forex Bureau Limited",
    "CBD Forex Bureau Limited",
    "Magnum Forex Bureau De Change Ltd",
    "Gala Forex Bureau Ltd",
    "Sisi Forex Bureau Limited",
    "Rand Forex Bureau Limited",
    "Boston Forex Bureau Limited",
    "Southend Forex Bureau Ltd",
    "Springs Forex Bureau Limited",
    "Credit Reference Bureau Africa Limited",
    "Metropol Credit Reference Bureau Limited",
    "Creditinfo Credit Reference Bureau Kenya Limited",
    "Dahabshiil Money Transfer Company Limited",
    "Amal Express Money Transfer Limited",
    "Iftin Express Money Transfer Limited",
    "Juba Express Money Transfer Limited",
    "Kaah Express Money Transfer Limited",
    "Amana Money Transfer Ltd",
    "Bakaal Express Money Transfer Ltd",
    "Safaricom Money Transfer Services Limited",
    "Hodan Global Money Remittance and Exchange Limited",
    "Tawakal Money Transfer Limited",
    "Flex Money Transfer Limited",
    "Taaj Money Transfer Limited",
    "Upesi Money Transfer Limited",
    "Real Value Money Transfer Limited",
    "PostBank Money Transfer Services Limited",
    "Postal Corporation of Kenya Money Transfer Services",
    "Airtel Money Transfer Limited",
    "Mobex Money Transfer Services Ltd",
    "Mukuru Money Transfer Limited",
    "Bakki Holdco Limited (Centum Group)",
    "Equity Group Holdings Limited",
    "HF Group Limited",
    "I&M Holdings Limited",
    "KCB Group PLC",
    "M Holdings Limited",
    "NCBA Group PLC",
    "Stanbic Holdings PLC",
    "Bank of China Limited - Kenya Representative Office",
    "Bank of Kigali Ltd - Kenya Representative Office",
    "FirstRand Bank limited - Kenya Representative Office",
    "HDFC Bank Limited - Kenya Representative Office",
    "Mauritius Commercial Bank Limited - Kenya Representative Office",
    "Nedbank Limited - Kenya Representative Office",
    "Co-operative Rabobank U.A - Kenya Representative Office",
    "Societe Generale - Kenya Representative Office",
    "BAHL - Kenya Representative Office",
  ];
  
  export const bankCodes = codes
    .map((code, i) => ({
      code: code,
      name: names[i],
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
  
export const memberTypes = [
    {code: "CM", name: "Chief Manager"},
    {code: "DM", name: "Senior Manager"},
    {code: "MG", name: "Manager"},
    {code: "AM", name: "Assistant Manager"},
]

export const sectorCode = [
  {code:"P2B05", name: "Mining and Quarrying"},
  {code:"P2B06", name: "Manufacturing"},
  {code:"P2B07", name: "Electricity, gas, steam and air conditioning supply"},
  {code:"P2B08", name: "Water supply: sewerage, waste management and remediation activities"},
  {code:"P2B09", name: "Construction"},
  {code:"P2B10", name: "Wholesale and retail trade; repair of motor vehicles and motorcycles"},
  {code:"P2B11", name: "Transportation and storage"},
  {code:"P2B12", name: "Accommodation and food service activities"},
  {code:"P2B13", name: "Information and communication"},
  {code:"P2B14", name: "Financial and insurance activities"},
  {code:"P2B15", name: "Real estate activities"},
  {code:"P2B16", name: "Professional, scientific and technical activities"},
  {code:"P2B17", name: "Administrative and support service activities"},
  {code:"P2B18", name: "Public administration and defence; compulsory social security"},
  {code:"P2B19", name: "Education"},
  {code:"P2B20", name: "Human health and social work activities"},
  {code:"P2B21", name: "Arts, entertainment and recreation"},
  {code:"P2B22", name: "Other service activities"},
  {code:"P2B23", name: "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use"},
  {code:"P2B24", name: "Activities of extraterritorial organizations and bodies"},
  {code:"P2B99", name: "Other sector"},
]

export const airtelBankAccnts = [
  {code: "0000001", name: "KCB Bank Kenya Limited", accounts:["1234999927", "1331078210"]},
  {code: "0000002", name: "Standard Chartered Bank Kenya Limited", accounts:["0100503550000", "01-060-035500-02"]},
  {code: "0000003", name: "ABSA Bank Kenya PLC", accounts:["2038497734", "2052446352"]},
  {code: "0000007", name: "NCBA Kenya PLC", accounts:["7922710015", "7922710028"]},
  {code: "0000011", name: "Co-operative Bank of Kenya Limited", accounts:["01136855534600", "01108555346002"]},
  {code: "0000031", name: "Stanbic Bank Kenya Limited", accounts:["0100005988149", "0100013831704"]},
  {code: "0000068", name: "Equity Bank Kenya Limited", accounts:["0810262907103", "0810285827623"]},
]

export const fraudCode = [
  { code: "IC01", name: "Wallet to wallet registered to registered" },
  { code: "IC02", name: "Wallet to wallet registered to unregistered" },
  { code: "IC03", name: "wallet to wallet unregistered to registered" },
  { code: "IC04", name: "Cross-network wallet to mobile number (Interop)" },
  { code: "IC05", name: "Local mobile wallet to international mobile money wallet" },
  { code: "IC06", name: "Bulk payment from business mobile money wallet to personal mobile money wallet" },
  { code: "IC07", name: "Bank account to mobile money wallet" },
  { code: "IC08", name: "Mobile money wallet to bank account" },
  { code: "IC09", name: "Agent cash and float" },
  { code: "IC10", name: "Deposit at branch or super agent" },
  { code: "IC11", name: "Withdrawal at branch or super agent" },
  { code: "IC12", name: "Float transfer to other agent" },
  { code: "IC13", name: "Mobile money wallet to merchant or business paybill" },
  { code: "IC14", name: "Mobile money wallet to till" },
  { code: "IC99", name: "Any other instrument type" },
  { code: "SG01", name: "P2P - Person to Person" },
  { code: "SG02", name: "P2B - Person to Business" },
  { code: "SG03", name: "P2G - Person to Government" },
  { code: "SG04", name: "B2P - Business to Person" },
  { code: "SG05", name: "B2B - Business to Business" },
  { code: "SG06", name: "B2G - Business to Government" },
  { code: "SG07", name: "G2P - Government to Person" },
  { code: "SG08", name: "G2G - Government to Business" },
  { code: "SG09", name: "G2B - Government to Government" },
  { code: "CI", name: "Individual" },
  { code: "CB", name: "Business" },
  { code: "CG", name: "Government/ Public entity" },
  { code: "SS", name: "Sim swap" },
  { code: "CONSEND", name: "Individuals conned into sending money" },
  { code: "CONPIN", name: "PIN theft" },
  { code: "CONIDEN", name: "Identity theft" },
  { code: "CONIMPER", name: "Impersonification" },
  { code: "SI", name: "Individual" },
  { code: "SB", name: "Business" },
  { code: "SG", name: "Government/ Public entity" },
  { code: "CTI", name: "Individual" },
  { code: "CTB", name: "Business" },
  { code: "CTG", name: "Government/ Public entity" },
  { code: "ATM", name: "ATM" },
  { code: "AG", name: "Agent" },
  { code: "INCNO", name: "No incident happened" },
];

export const fraudCategoryTypeCode = [
  {code: "FCT01", name: "Actual"},
  {code: "FCT02", name: "Attempted"},
  {code: "FCT03", name: "Neither attempted nor actual"},
]

export const victimCategoryCode = [
  {code: "VCCD01", name: "Individual"},
  {code: "VCCD02", name: "Agent"},
  {code: "VCCD03", name: "Bank"},
  {code: "VCCD04", name: "Mobile PSP"},
  {code: "VCCD05", name: "None, no fraud occured"},
  {code: "VCCD99", name: "Any Other"},
]

export const victimAttributeCode = [
  {code: "VICT01", name: "Name"},
  {code: "VICT02", name: "Age"},
  {code: "VICT03", name: "Contact number"},
  {code: "VICT04", name: "Physical location"},
  {code: "VICT05", name: "Education level"},
  {code: "VICT99", name: "Other details"},
]

export const incidentModeData = [
  {code: "ICDT01", name: "Malware"},
  {code: "ICDT02", name: "Exploits"},
  {code: "ICDT03", name: "Phishing"},
  {code: "ICDT04", name: "No incident happened"},
  {code: "ICDT99", name: "Others"},
]

export const employmentType = [
  {code:"ETC01", name: "Full-time employment"},
  {code:"ETC02", name: "Part-time employment"},
  {code:"ETC03", name: "Casual employment"},
  {code:"ETC04", name: "Contract employment"},
  {code:"ETC05", name: "Apprenticeship"},
  {code:"ETC06", name: "Traineeship"},
  {code:"ETC07", name: "Employment on commission"},
  {code:"ETC08", name: "Probation"},
  {code:"ETC99", name: "Any other"},
]

export const disclosureCodes = [
  {code:"DDC01", name: "Shareholdings"},
  {code:"DDC02", name: "Family relationships"},
  {code:"DDC03", name: "Convicted of an offence"},
  {code:"DDC99", name: "Any other"},
]

export const thirdPartyOwnedCategoryData = [
  {code: "TPOCC01", name: "Mobile PSP"},
  {code: "TPOCC02", name: "Bank"},
  {code: "TPOCC03", name: "Switches"},
  {code: "TPOCC04", name: "Gateway"},
  {code: "TPOCC05", name: "Business merchants"},
  {code: "TPOCC06", name: "Utility merchants"},
  {code: "TPOCC99", name: "Specify, other"},
]

export const productType = [
  {code: "B2C", name: "Bank to Customer"},
  {code: "C2B", name: "Customer to Business"},
  {code: "P2P", name: "Person to Person"},
  {code: "BTE", name: "Bank to Wallet"},
  {code: "CTB", name: "Wallet to Bank"},
  {code: "PRODT01", name: "Mobile loans"},
  {code: "PRODT02", name: "Buy Airtime"},
  {code: "NPRODT", name: "No Product affected because no system unavailability was experienced"},
  {code: "OS", name: "Others"},
]

export const systemUnavailabilityTypeCode = [
  { code: "SSTC01", name: "Total downtime"},
  { code: "SSTC02", name: "Intermittent downtime"},
  { code: "SSTC03", name: "No interruption experienced"},
  { code: "SSTC99", name: "Other system availability type"},
]

export const systemInterruptionCauseCode = [
  { code: "ICD01", name: "Network outage"},
  { code: "ICD02", name: "Vandalism"},
  { code: "ICD03", name: "Power outage"},
  { code: "ICD04", name: "Cyber attack"},
  { code: "ICD05", name: "No interruption experienced"},
  { code: "ICD99", name: "Other"},
]

export const severityInterruptionCode = [
  { code: "DT01", name: "Low"},
  { code: "DT02", name: "Medium"},
  { code: "DT03", name: "High"},
  { code: "DT04", name: "None"},
]

export const recoveryTimeCode = [
  { code: "RCD01", name: "0 - 5 Minutes"},
  { code: "RCD02", name: "6 - 10 Minutes"},
  { code: "RCD03", name: "11 - 15 Minutes"},
  { code: "RCD04", name: "16 - 20 Minutes"},
  { code: "RCD05", name: "21 - 25 Minutes"},
  { code: "RCD06", name: "26 - 30 Minutes"},
  { code: "RCD07", name: "31 - 60 Minutes"},
  { code: "RCD08", name: ">1 - 2 Hours"},
  { code: "RCD09", name: "No system unavailability"},
  { code: "RCD99", name: "Others"},
]