const subCountyCodes = [
    { code: "0101", name: "CHANGAMWE" },
    { code: "0102", name: "JOMVU" },
    { code: "0103", name: "KISAUNI" },
    { code: "0104", name: "LIKONI" },
    { code: "0105", name: "MVITA" },
    { code: "0106", name: "NYALI" },
    { code: "0201", name: "KINANGO" },
    { code: "0202", name: "LUNGA LUNGA" },
    { code: "0203", name: "MATUGA" },
    { code: "0204", name: "MSAMBWENI" },
    { code: "0205", name: "SAMBURU" },
    { code: "0301", name: "CHONYI" },
    { code: "0302", name: "GANZE" },
    { code: "0303", name: "KALOLENI" },
    { code: "0304", name: "KAUMA" },
    { code: "0305", name: "KILIFI NORTH" },
    { code: "0306", name: "KILIFI SOUTH" },
    { code: "0307", name: "MAGARINI" },
    { code: "0308", name: "MALINDI" },
    { code: "0309", name: "RABAI" },
    { code: "0401", name: "TANA DELTA" },
    { code: "0402", name: "TANA NORTH" },
    { code: "0403", name: "TANA RIVER" },
    { code: "0501", name: "LAMU EAST" },
    { code: "0502", name: "LAMU WEST" },
    { code: "0601", name: "MWATATE" },
    { code: "0602", name: "TAITA" },
    { code: "0603", name: "TAVETA" },
    { code: "0604", name: "VOI" },
    { code: "0701", name: "BALAMBALA" },
    { code: "0702", name: "DADAAB" },
    { code: "0703", name: "FAFI" },
    { code: "0704", name: "GARISSA" },
    { code: "0705", name: "HULUGHO" },
    { code: "0706", name: "IJARA" },
    { code: "0707", name: "LAGDERA" },
    { code: "0801", name: "BUNA" },
    { code: "0802", name: "ELDAS" },
    { code: "0803", name: "HABASWEIN" },
    { code: "0804", name: "TARBAJ" },
    { code: "0805", name: "WAJIR EAST" },
    { code: "0806", name: "WAJIR NORTH" },
    { code: "0807", name: "WAJIR SOUTH" },
    { code: "0808", name: "WAJIR WEST" },
    { code: "0901", name: "MANDERA WEST" },
    { code: "0902", name: "BANISA" },
    { code: "0903", name: "KOTULO" },
    { code: "0904", name: "LAFEY" },
    { code: "0905", name: "MANDERA CENTRAL" },
    { code: "0906", name: "MANDERA EAST" },
    { code: "0907", name: "MANDERA NORTH" },
    { code: "1001", name: "LOIYANGALANI" },
    { code: "1002", name: "MARSABIT CENTRAL" },
    { code: "1003", name: "MARSABIT NORTH" },
    { code: "1004", name: "MARSABIT SOUTH" },
    { code: "1005", name: "MOYALE" },
    { code: "1006", name: "NORTH HORR" },
    { code: "1007", name: "SOLOLO" },
    { code: "1101", name: "GARBATULLA" },
    { code: "1102", name: "ISIOLO" },
    { code: "1103", name: "MERTI" },
    { code: "1202", name: "BUURI WEST" },
    { code: "1203", name: "IGEMBE CENTRAL" },
    { code: "1204", name: "IGEMBE NORTH" },
    { code: "1205", name: "IGEMBE SOUTH" },
    { code: "1206", name: "IMENTI NORTH" },
    { code: "1207", name: "IMENTI SOUTH" },
    { code: "1208", name: "MERU CENTRAL" },
    { code: "1209", name: "TIGANIA CENTRAL" },
    { code: "1210", name: "TIGANIA EAST" },
    { code: "1211", name: "TIGANIA WEST" },
    { code: "1301", name: "IGAMBANG'OMBE" },
    { code: "1302", name: "MAARA" },
    { code: "1303", name: "MERU SOUTH" },
    { code: "1304", name: "THARAKA NORTH" },
    { code: "1305", name: "THARAKA SOUTH" },
    { code: "1401", name: "EMBU EAST" },
    { code: "1402", name: "EMBU NORTH" },
    { code: "1403", name: "EMBU WEST" },
    { code: "1404", name: "MBEERE SOUTH" },
    { code: "1405", name: "MBEERE NORTH" },
    { code: "1501", name: "IKUTHA" },
    { code: "1502", name: "KATULANI" },
    { code: "1503", name: "KISASI" },
    { code: "1504", name: "KITUI CENTRAL" },
    { code: "1505", name: "KITUI WEST" },
    { code: "1506", name: "KYUSO" },
    { code: "1507", name: "LOWER YATTA" },
    { code: "1508", name: "MATINYANI" },
    { code: "1509", name: "MIGWANI" },
    { code: "1510", name: "MUMONI" },
    { code: "1511", name: "MUTITU" },
    { code: "1512", name: "MUTITU NORTH" },
    { code: "1513", name: "MUTOMO" },
    { code: "1514", name: "MWINGI CENTRAL" },
    { code: "1515", name: "MWINGI EAST" },
    { code: "1516", name: "NZAMBANI" },
    { code: "1517", name: "THAGICU" },
    { code: "1518", name: "TSEIKURU" },
    { code: "1601", name: "ATHI RIVER" },
    { code: "1602", name: "KALAMA" },
    { code: "1603", name: "KANGUNDO" },
    { code: "1604", name: "KATHIANI" },
    { code: "1605", name: "MACHAKOS" },
    { code: "1606", name: "MASINGA" },
    { code: "1607", name: "MATUNGULU" },
    { code: "1608", name: "MWALA" },
    { code: "1609", name: "YATTA" },
    { code: "1701", name: "KATHONZWENI" },
    { code: "1702", name: "KIBWEZI" },
    { code: "1703", name: "KILUNGU" },
    { code: "1704", name: "MAKINDU" },
    { code: "1705", name: "MAKUENI" },
    { code: "1706", name: "MBOONI EAST" },
    { code: "1707", name: "MBOONI WEST" },
    { code: "1708", name: "MUKAA" },
    { code: "1709", name: "NZAUI" },
    { code: "1801", name: "KINANGOP" },
    { code: "1802", name: "NYANDARUA SOUTH" },
    { code: "1803", name: "MIRANGINE" },
    { code: "1804", name: "KIPIPIRI" },
    { code: "1805", name: "NYANDARUA CENTRAL" },
    { code: "1806", name: "NYANDARUA WEST" },
    { code: "1807", name: "NYANDARUA NORTH" },
    { code: "1901", name: "TETU" },
    { code: "1902", name: "KIENI EAST" },
    { code: "1903", name: "KIENI WEST" },
    { code: "1904", name: "MATHIRA EAST" },
    { code: "1905", name: "MATHIRA WEST" },
    { code: "1906", name: "NYERI SOUTH" },
    { code: "1907", name: "MUKURWE-INI" },
    { code: "1908", name: "NYERI CENTRAL" },
    { code: "2001", name: "KIRINYAGA CENTRAL" },
    { code: "2002", name: "KIRINYAGA EAST" },
    { code: "2003", name: "KIRINYAGA WEST" },
    { code: "2004", name: "MWEA EAST" },
    { code: "2005", name: "MWEA WEST" },
    { code: "2101", name: "MURANG'A EAST" },
    { code: "2102", name: "KANGEMA" },
    { code: "2103", name: "MATHIOYA" },
    { code: "2104", name: "KAHURO" },
    { code: "2105", name: "MURANG'A SOUTH" },
    { code: "2106", name: "GATANGA" },
    { code: "2107", name: "KIGUMO" },
    { code: "2108", name: "KANDARA" },
    { code: "2201", name: "GATUNDU NORTH" },
    { code: "2202", name: "GATUNDU SOUTH" },
    { code: "2203", name: "GITHUNGURI" },
    { code: "2204", name: "JUJA" },
    { code: "2205", name: "KABETE" },
    { code: "2206", name: "KIAMBAA" },
    { code: "2207", name: "KIAMBU" },
    { code: "2208", name: "KIKUYU" },
    { code: "2209", name: "LARI" },
    { code: "2210", name: "LIMURU" },
    { code: "2211", name: "RUIRU" },
    { code: "2212", name: "THIKA EAST" },
    { code: "2213", name: "THIKA WEST" },
    { code: "2301", name: "KIBISH" },
    { code: "2302", name: "LOIMA" },
    { code: "2303", name: "TURKANA CENTRAL" },
    { code: "2304", name: "TURKANA EAST" },
    { code: "2305", name: "TURKANA NORTH" },
    { code: "2306", name: "TURKANA SOUTH" },
    { code: "2307", name: "TURKANA WEST" },
    { code: "2401", name: "KIPKOMO" },
    { code: "2402", name: "POKOT CENTRAL" },
    { code: "2403", name: "POKOT NORTH" },
    { code: "2404", name: "POKOT SOUTH" },
    { code: "2405", name: "WEST POKOT" },
    { code: "2501", name: "SAMBURU CENTRAL" },
    { code: "2502", name: "SAMBURU EAST" },
    { code: "2503", name: "SAMBURU NORTH" },
    { code: "2601", name: "TRANS NZOIA WEST" },
    { code: "2602", name: "TRANS NZOIA EAST" },
    { code: "2603", name: "KWANZA" },
    { code: "2604", name: "ENDEBESS" },
    { code: "2605", name: "KIMININI" },
    { code: "2701", name: "AINABKOI" },
    { code: "2702", name: "KAPSERET" },
    { code: "2703", name: "KESSES" },
    { code: "2704", name: "MOIBEN" },
    { code: "2705", name: "SOY" },
    { code: "2706", name: "TURBO" },
    { code: "2801", name: "KEIYO NORTH" },
    { code: "2802", name: "KEIYO SOUTH" },
    { code: "2803", name: "MARAKWET EAST" },
    { code: "2804", name: "MARAKWET WEST" },
    { code: "2901", name: "CHESUMEI" },
    { code: "2902", name: "NANDI CENTRAL" },
    { code: "2903", name: "NANDI EAST" },
    { code: "2904", name: "NANDI NORTH" },
    { code: "2905", name: "NANDI SOUTH" },
    { code: "2906", name: "TINDERET" },
    { code: "3001", name: "BARINGO CENTRAL" },
    { code: "3002", name: "BARINGO NORTH" },
    { code: "3003", name: "EAST POKOT" },
    { code: "3004", name: "KOIBATEK" },
    { code: "3005", name: "MARIGAT" },
    { code: "3006", name: "MOGOTIO" },
    { code: "3007", name: "TIATY EAST" },
    { code: "3008", name: "LAKE BARINGO" },
    { code: "3101", name: "LAIKIPIA CENTRAL" },
    { code: "3102", name: "LAIKIPIA EAST" },
    { code: "3103", name: "LAIKIPIA NORTH" },
    { code: "3104", name: "LAIKIPIA WEST" },
    { code: "3105", name: "NYAHURURU" },
    { code: "3201", name: "GILGIL" },
    { code: "3202", name: "KURESOI NORTH" },
    { code: "3203", name: "KURESOI SOUTH" },
    { code: "3204", name: "MOLO" },
    { code: "3205", name: "NAIVASHA" },
    { code: "3206", name: "NAKURU EAST" },
    { code: "3207", name: "NAKURU NORTH" },
    { code: "3208", name: "NAKURU WEST" },
    { code: "3209", name: "NJORO" },
    { code: "3210", name: "RONGAI" },
    { code: "3211", name: "SUBUKIA" },
    { code: "3301", name: "NAROK EAST" },
    { code: "3302", name: "NAROK NORTH" },
    { code: "3303", name: "NAROK SOUTH" },
    { code: "3304", name: "NAROK WEST" },
    { code: "3305", name: "TRANS MARA EAST" },
    { code: "3306", name: "TRANS MARA WEST" },
    { code: "3401", name: "ISINYA" },
    { code: "3402", name: "KAJIADO CENTRAL" },
    { code: "3403", name: "KAJIADO NORTH" },
    { code: "3404", name: "KAJIADO WEST" },
    { code: "3405", name: "LOITOKITOK" },
    { code: "3406", name: "MASHUURU" },
    { code: "3501", name: "BELGUT" },
    { code: "3502", name: "BURETI" },
    { code: "3503", name: "KERICHO EAST" },
    { code: "3504", name: "KIPKELION" },
    { code: "3505", name: "LONDIANI" },
    { code: "3506", name: "SOIN SIGOWET" },
    { code: "3601", name: "BOMET EAST" },
    { code: "3602", name: "CHEPALUNGU" },
    { code: "3603", name: "KONOIN" },
    { code: "3604", name: "SOTIK" },
    { code: "3605", name: "BOMET CENTRAL" },
    { code: "3701", name: "BUTERE" },
    { code: "3702", name: "KAKAMEGA CENTRAL" },
    { code: "3703", name: "KAKAMEGA EAST" },
    { code: "3704", name: "KAKAMEGA NORTH" },
    { code: "3705", name: "KAKAMEGA SOUTH" },
    { code: "3706", name: "KHWISERO" },
    { code: "3707", name: "LIKUYANI" },
    { code: "3708", name: "LUGARI" },
    { code: "3709", name: "MATETE" },
    { code: "3710", name: "MATUNGU" },
    { code: "3711", name: "MUMIAS EAST" },
    { code: "3712", name: "MUMIAS WEST" },
    { code: "3713", name: "NAVAKHOLO" },
    { code: "3801", name: "EMUHAYA" },
    { code: "3802", name: "VIHIGA" },
    { code: "3803", name: "SABATIA" },
    { code: "3804", name: "LUANDA" },
    { code: "3805", name: "HAMISI" },
    { code: "3901", name: "BUMULA" },
    { code: "3902", name: "BUNGOMA CENTRAL" },
    { code: "3903", name: "BUNGOMA EAST" },
    { code: "3904", name: "BUNGOMA NORTH" },
    { code: "3905", name: "BUNGOMA SOUTH" },
    { code: "3906", name: "CHEPTAIS" },
    { code: "3907", name: "KIMILILI" },
    { code: "3909", name: "BUNGOMA WEST" },
    { code: "3910", name: "TONGAREN" },
    { code: "3911", name: "WEBUYE WEST" },
    { code: "3912", name: "MT ELGON FOREST" },
    { code: "4001", name: "BUNYALA" },
    { code: "4002", name: "BUSIA" },
    { code: "4003", name: "BUTULA" },
    { code: "4004", name: "NAMBALE" },
    { code: "4005", name: "SAMIA" },
    { code: "4006", name: "TESO NORTH" },
    { code: "4007", name: "TESO SOUTH" },
    { code: "4101", name: "SIAYA" },
    { code: "4102", name: "GEM" },
    { code: "4103", name: "UGENYA" },
    { code: "4104", name: "UGUNJA" },
    { code: "4105", name: "BONDO" },
    { code: "4106", name: "RARIEDA" },
    { code: "4201", name: "KISUMU EAST" },
    { code: "4202", name: "KISUMU CENTRAL" },
    { code: "4203", name: "KISUMU WEST" },
    { code: "4204", name: "SEME" },
    { code: "4205", name: "MUHORONI" },
    { code: "4206", name: "NYANDO" },
    { code: "4207", name: "NYAKACH" },
    { code: "4301", name: "HOMA BAY" },
    { code: "4302", name: "NDHIWA" },
    { code: "4303", name: "RACHUONYO NORTH" },
    { code: "4304", name: "RACHUONYO EAST" },
    { code: "4305", name: "RACHUONYO SOUTH" },
    { code: "4306", name: "RANGWE" },
    { code: "4307", name: "SUBA NORTH" },
    { code: "4308", name: "SUBA SOUTH" },
    { code: "4401", name: "AWENDO" },
    { code: "4402", name: "KURIA EAST" },
    { code: "4403", name: "KURIA WEST" },
    { code: "4404", name: "NYATIKE" },
    { code: "4405", name: "RONGO" },
    { code: "4406", name: "SUNA EAST" },
    { code: "4407", name: "SUNA WEST" },
    { code: "4408", name: "URIRI" },
    { code: "4501", name: "ETAGO" },
    { code: "4502", name: "GUCHA" },
    { code: "4503", name: "GUCHA SOUTH" },
    { code: "4504", name: "KENYENYA" },
    { code: "4505", name: "KISII CENTRAL" },
    { code: "4506", name: "KISII SOUTH" },
    { code: "4507", name: "KITUTU CENTRAL" },
    { code: "4508", name: "MARANI" },
    { code: "4509", name: "MASABA SOUTH" },
    { code: "4510", name: "NYAMACHE" },
    { code: "4511", name: "SAMETA" },
    { code: "4601", name: "BORABU" },
    { code: "4602", name: "MANGA" },
    { code: "4603", name: "MASABA NORTH" },
    { code: "4604", name: "NYAMIRA NORTH" },
    { code: "4605", name: "NYAMIRA SOUTH" },
    { code: "4701", name: "DAGORETTI" },
    { code: "4702", name: "EMBAKASI" },
    { code: "4703", name: "KAMUKUNJI" },
    { code: "4704", name: "KASARANI" },
    { code: "4705", name: "KIBRA" },
    { code: "4706", name: "LANG'ATA" },
    { code: "4707", name: "MAKADARA" },
    { code: "4708", name: "MATHARE" },
    { code: "4709", name: "NJIRU" },
    { code: "4710", name: "STAREHE" },
    { code: "4711", name: "WESTLANDS" },
    
  ];
  
  function sortByName(arr) {
    return [...arr.sort((a, b) => a.name.localeCompare(b.name)), {
        code: "1000",
        name: "Sub county field where not applicable because of the nature of business",
      }];
  }
  
export const subCountyArr = sortByName(subCountyCodes);

export const educationLevel = [
    {code: "ELAC01", name: "Primary"},
    {code: "ELAC02", name: "Secondary"},
    {code: "ELAC03", name: "Bachelors"},
    {code: "ELAC04", name: "Masters"},
    {code: "ELAC05", name: "PhD"},
    {code: "ELAC06", name: "Professional education"},
    {code: "ELAC07", name: "Member of professional body"},
    {code: "ELAC08", name: "Education level not applicable"},
    {code: "ELAC99", name: "Others"},
]

export const complaintType = [
    { code: "CCS01", name: "Unexpected charges" },
    { code: "CCS02", name: "Undisclosed charges" },
    { code: "CCS03", name: "Non-receipt of funds sent" },
    { code: "CCS04", name: "Sending failure" },
    { code: "CCS05", name: "Product/service not working or unavailable" },
    { code: "CCS06", name: "Product issued to customer not the right one s/he needed" },
    { code: "CCS07", name: "Product terms and conditions not displayed or given to customer" },
    { code: "CCS08", name: "Product terms and conditions not explained clearly and in a simple manner" },
    { code: "CCS09", name: "Termination of service without prior and sufficient notice" },
    { code: "CCS10", name: "Paid for service but it has not been provided or activated" },
    { code: "CCS11", name: "Unauthorised and excessive sending of promotional text messages" },
    { code: "CCS12", name: "Lack of clear channel for making a complaint" },
    { code: "CCS13", name: "Resolution of complaint took/takes excessively long" },
    { code: "CCS14", name: "Lack of a clear recourse mechanism" },
    { code: "CCS15", name: "Customer's data & info disclosed to other parties without prior consent" },
    { code: "CCS99", name: "Other complaint type" }
  ];
  
export const pspName = [
    { code: "0800002", name: "Airtel Money Kenya Limited" },
    { code: "0800001", name: "Safaricom Plc" },
    { code: "0800003", name: "Telkom Kenya Limited" },
    { code: "0800004", name: "Mobile pay Limited" },
    { code: "0800005", name: "Kenswitch Limited" },
    { code: "0800006", name: "Interswitch East Africa (K) Limited" },
    { code: "0800007", name: "Integrated Payment Services Limited" },
    { code: "0800008", name: "Viewtech Limited" },
    { code: "0800009", name: "Web Tribe Limited" },
    { code: "0800010", name: "Finserve Africa Limited" },
    { code: "0800011", name: "Cellulant Kenya Limited" },
    { code: "0800012", name: "Pesapal Limited" },
    { code: "0800013", name: "Fivespot Limited" },
    { code: "0800014", name: "Craft Silicon Limited" },
    { code: "0800015", name: "Virtual Pay International Limited" },
    { code: "0800016", name: "Direct pay Limited" },
    { code: "0800017", name: "Pesawise Services Limited" },
    { code: "0800018", name: "Paystack Payments Kenya Limited" },
    { code: "0800019", name: "Wakandi Kenya Limited" },
    { code: "0800020", name: "Kenya Airports Parking Services (KAPS) Limited" },
    { code: "0800021", name: "Loop Payco Limited" },
    { code: "0800022", name: "DLocal Payments Kenya Limited" },
    { code: "0800023", name: "Pesaflow Limited" },
    { code: "0800024", name: "Kenya Commerce Exchange Service Bureau Limited" },
    { code: "0800025", name: "PayU Kenya Limited" },
    { code: "0800026", name: "Dolcepay Kenya Limited" },
    { code: "0800027", name: "Unlimint Kenya Limited" },
    { code: "0800028", name: "Gladys Technologies Limited" },
    { code: "0800029", name: "Mamlaka Hub and Spoke Limited" },
    { code: "0800030", name: "Eclectics International Limited" },
    { code: "0800031", name: "Jumia Payment Services Kenya Limited" }
  ];

  export const denominationCodes = [
    {code: "KESB1000", name: "1,000/- New Generation Note"},
    {code: "KESB500", name: "500/- New Generation Note"},
    {code: "KESB200", name: "200/- New Generation Note"},
    {code: "KESB100", name: "100/- New Generation Note"},
    {code: "KESB50", name: "50/- New Generation Note"},
    {code: "KES1000", name: "1000 - Old Generation Note"},
    {code: "KES500", name: "500 - Old Generation Note"},
    {code: "KES200", name: "200 - Old Generation Note"},
    {code: "KES100", name: "100 - Old Generation Note"},
    {code: "KES50", name: "50 - Old Generation Note"},
    {code: "KES20", name: "20 - Old Generation Note"},
    {code: "KES10", name: "10 - Old Generation Note"},
    {code: "KES5", name: "5 - Old Generation Note"},
    {code: "KES40", name: "40/- Old or New Generation Coin"},
    {code: "KES.20", name: "20/- Old or New Generation Coin"},
    {code: "KES.10", name: "10/- Old or New Generation Coin"},
    {code: "KES.5", name: "5/- Old or New Generation Coin"},
    {code: "KES1", name: "1/- Old or New Generation Coin"},
    {code: "KES.050", name: "0.5"},
    {code: "Nil", name: "KES.NA"},
  ]

export const institutionCodes = [
  {code: ""}
]

export const trustAccDrTypeCode = [
  {code: "DBT01", name: "Banks charges"},
  {code: "DBT02", name: "Management fees"},
  {code: "DBT03", name: "Stamp duty"},
  {code: "DBT04", name: "Donations"},
  {code: "DBT05", name: "Custody fees"},
  {code: "DBT06", name: "Audit fees"},
  {code: "DBT07", name: "Withholding taxes"},
  {code: "DBT08", name: "Field not applicable"},
  {code: "DBT99", name: "Any others debit type"},
]

export const trustFundPlacement = [
  {code: "TFP01", name: "Cash holdings (Fixed Deposit)"},
  {code: "TFP02", name: "Cash holdings (Current)"},
  {code: "TFP03", name: "Cash holdings (Fixed Deposit) in foreign currency account"},
  {code: "TFP04", name: "Cash holdings (Current) in foreign currency account"},
  {code: "TFP05", name: "Treasury bills"},
  {code: "TFP06", name: "Treasury bonds"},
  {code: "TFP99", name: "Any other"},
]
