import { lazy } from 'react'

export const BandCode = lazy(()=> import("./pages/PSP/BandCode"))
export const BandCodes = lazy(()=> import("./pages/PSP/BandCodes"))
export const MobilePSP = lazy(()=> import("./pages/PSP/MobilePSP"))
export const PSPCybersecurity = lazy(()=> import("./pages/PSP/PSPCybersecurity"))
export const PSPIncidentFraud = lazy(()=> import("./pages/PSP/PSPIncidentFraud"))
export const PSPScheduleOfCustomerComplaints = lazy(()=> import("./pages/PSP/PSPScheduleOfCustomerComplaints"))
export const PSPScheduleOfSystemStabilityAndInterruption = lazy(()=> import("./pages/PSP/PSPScheduleOfSystemStabilityAndInterruption"))
export const PSPScheduleOfDirectors = lazy(()=> import("./pages/PSP/PSPScheduleOfDirectors"))
export const PSPScheduleOfSeniorMgt = lazy(()=> import("./pages/PSP/PSPScheduleOfSeniorMgt"))
export const PSPScheduleOfShareholders = lazy(()=> import("./pages/PSP/PSPScheduleOfShareholders"))
export const PSPScheduleOfTrustees = lazy(()=> import("./pages/PSP/PSPScheduleOfTrustees"))
export const TrustAccountDetails = lazy(()=> import("./pages/PSP/TrustAccountDetails"))
export const TrustAccountPlacement = lazy(()=> import("./pages/PSP/TrustAccountPlacement"))

export const DirectorMgt = lazy(()=> import("./pages/BSD/DirectorMgt"))
export const ExchangeRates = lazy(()=> import("./pages/BSD/ExchangeRates"))
export const FinPosition = lazy(()=> import("./pages/BSD/FinPosition"))
export const ForeignExchangePosition = lazy(()=> import("./pages/BSD/ForeignExchangePosition"))
export const OutletInfo = lazy(()=> import("./pages/BSD/OutletInfo"))
export const ShareholdersInfo = lazy(()=> import("./pages/BSD/ShareholdersInfo"))

export const Home = lazy(()=> import("./pages/Home"))
export const Layout = lazy(()=> import("./pages/Layout"))
export const Login = lazy(()=> import("./pages/Login"))
export const Signup = lazy(()=> import("./pages/Signup"))
export const UserApprovals = lazy(()=> import("./pages/UserApprovals"))
export const VerificationNotification = lazy(()=> import("./pages/VerificationNotification"))